# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wizard.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.logo = QtWidgets.QLineEdit(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(112, 123, 291, 20))
        self.logo.setObjectName("logo")
        self.generate = QtWidgets.QPushButton(self.centralwidget)
        self.generate.setGeometry(QtCore.QRect(10, 530, 171, 41))
        self.generate.setAutoRepeat(False)
        self.generate.setAutoExclusive(False)
        self.generate.setObjectName("generate")
        self.console = QtWidgets.QTextBrowser(self.centralwidget)
        self.console.setGeometry(QtCore.QRect(450, 10, 731, 561))
        self.console.setObjectName("console")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(14, 39, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLineWidth(2)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(14, 81, 104, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLineWidth(2)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(14, 123, 79, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setLineWidth(2)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(14, 165, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setLineWidth(2)
        self.label_4.setObjectName("label_4")
        self.browseidir = QtWidgets.QPushButton(self.centralwidget)
        self.browseidir.setGeometry(QtCore.QRect(412, 39, 31, 23))
        self.browseidir.setObjectName("browseidir")
        self.browseodir = QtWidgets.QPushButton(self.centralwidget)
        self.browseodir.setGeometry(QtCore.QRect(412, 80, 31, 23))
        self.browseodir.setObjectName("browseodir")
        self.browselogo = QtWidgets.QPushButton(self.centralwidget)
        self.browselogo.setGeometry(QtCore.QRect(412, 123, 31, 23))
        self.browselogo.setObjectName("browselogo")
        self.idir = QtWidgets.QLineEdit(self.centralwidget)
        self.idir.setGeometry(QtCore.QRect(112, 39, 291, 20))
        self.idir.setObjectName("idir")
        self.odir = QtWidgets.QLineEdit(self.centralwidget)
        self.odir.setGeometry(QtCore.QRect(112, 81, 291, 20))
        self.odir.setObjectName("odir")
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(112, 165, 151, 20))
        self.name.setObjectName("name")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(12, 218, 378, 19))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.recursive = QtWidgets.QCheckBox(self.layoutWidget)
        self.recursive.setObjectName("recursive")
        self.horizontalLayout.addWidget(self.recursive)
        self.verbose = QtWidgets.QCheckBox(self.layoutWidget)
        self.verbose.setObjectName("verbose")
        self.horizontalLayout.addWidget(self.verbose)
        self.usage = QtWidgets.QCheckBox(self.layoutWidget)
        self.usage.setObjectName("usage")
        self.horizontalLayout.addWidget(self.usage)
        self.code = QtWidgets.QCheckBox(self.layoutWidget)
        self.code.setObjectName("code")
        self.horizontalLayout.addWidget(self.code)
        self.resConsole = QtWidgets.QPushButton(self.centralwidget)
        self.resConsole.setGeometry(QtCore.QRect(360, 520, 81, 23))
        self.resConsole.setObjectName("resConsole")
        self.resAll = QtWidgets.QPushButton(self.centralwidget)
        self.resAll.setGeometry(QtCore.QRect(360, 550, 81, 23))
        self.resAll.setObjectName("resAll")
        self.dumpLog = QtWidgets.QPushButton(self.centralwidget)
        self.dumpLog.setGeometry(QtCore.QRect(360, 490, 81, 23))
        self.dumpLog.setObjectName("dumpLog")
        self.odir.raise_()
        self.name.raise_()
        self.layoutWidget.raise_()
        self.logo.raise_()
        self.generate.raise_()
        self.console.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.idir.raise_()
        self.browseidir.raise_()
        self.browseodir.raise_()
        self.browselogo.raise_()
        self.resConsole.raise_()
        self.resAll.raise_()
        self.dumpLog.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.idir, self.browseidir)
        MainWindow.setTabOrder(self.browseidir, self.odir)
        MainWindow.setTabOrder(self.odir, self.browseodir)
        MainWindow.setTabOrder(self.browseodir, self.logo)
        MainWindow.setTabOrder(self.logo, self.browselogo)
        MainWindow.setTabOrder(self.browselogo, self.name)
        MainWindow.setTabOrder(self.name, self.recursive)
        MainWindow.setTabOrder(self.recursive, self.verbose)
        MainWindow.setTabOrder(self.verbose, self.usage)
        MainWindow.setTabOrder(self.usage, self.code)
        MainWindow.setTabOrder(self.code, self.generate)
        MainWindow.setTabOrder(self.generate, self.console)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.generate.setText(_translate("MainWindow", "Generate Documentation"))
        self.label.setText(_translate("MainWindow", "Input directory"))
        self.label_2.setText(_translate("MainWindow", "Output directory"))
        self.label_3.setText(_translate("MainWindow", "Project Logo"))
        self.label_4.setText(_translate("MainWindow", "Project Name"))
        self.browseidir.setText(_translate("MainWindow", "..."))
        self.browseodir.setText(_translate("MainWindow", "..."))
        self.browselogo.setText(_translate("MainWindow", "..."))
        self.recursive.setText(_translate("MainWindow", "Recursive scan"))
        self.verbose.setText(_translate("MainWindow", "Verbose mode"))
        self.usage.setText(_translate("MainWindow", "Check usage"))
        self.code.setText(_translate("MainWindow", "Append Code"))
        self.resConsole.setText(_translate("MainWindow", "Reset console"))
        self.resAll.setText(_translate("MainWindow", "Reset All"))
        self.dumpLog.setText(_translate("MainWindow", "Dump log"))

