# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wizard.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1269, 752)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(46456, 46456))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.console = QtWidgets.QTextBrowser(self.widget)
        self.console.setObjectName("console")
        self.verticalLayout.addWidget(self.console)
        self.overallprogess = QtWidgets.QProgressBar(self.widget)
        self.overallprogess.setProperty("value", 0)
        self.overallprogess.setObjectName("overallprogess")
        self.verticalLayout.addWidget(self.overallprogess)
        self.gridLayout_4.addWidget(self.widget, 0, 1, 3, 1)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLineWidth(2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.browseidir = QtWidgets.QPushButton(self.widget_2)
        self.browseidir.setObjectName("browseidir")
        self.gridLayout.addWidget(self.browseidir, 0, 2, 1, 1)
        self.odir = QtWidgets.QLineEdit(self.widget_2)
        self.odir.setObjectName("odir")
        self.gridLayout.addWidget(self.odir, 1, 1, 1, 1)
        self.browseodir = QtWidgets.QPushButton(self.widget_2)
        self.browseodir.setObjectName("browseodir")
        self.gridLayout.addWidget(self.browseodir, 1, 2, 1, 1)
        self.logo = QtWidgets.QLineEdit(self.widget_2)
        self.logo.setObjectName("logo")
        self.gridLayout.addWidget(self.logo, 2, 1, 1, 1)
        self.browselogo = QtWidgets.QPushButton(self.widget_2)
        self.browselogo.setObjectName("browselogo")
        self.gridLayout.addWidget(self.browselogo, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setLineWidth(2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.idir = QtWidgets.QLineEdit(self.widget_2)
        self.idir.setObjectName("idir")
        self.gridLayout.addWidget(self.idir, 0, 1, 1, 1)
        self.name = QtWidgets.QLineEdit(self.widget_2)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setLineWidth(2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLineWidth(2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verbose = QtWidgets.QCheckBox(self.widget_3)
        self.verbose.setObjectName("verbose")
        self.gridLayout_2.addWidget(self.verbose, 0, 1, 1, 1)
        self.code = QtWidgets.QCheckBox(self.widget_3)
        self.code.setObjectName("code")
        self.gridLayout_2.addWidget(self.code, 0, 3, 1, 1)
        self.recursive = QtWidgets.QCheckBox(self.widget_3)
        self.recursive.setObjectName("recursive")
        self.gridLayout_2.addWidget(self.recursive, 0, 0, 1, 1)
        self.usage = QtWidgets.QCheckBox(self.widget_3)
        self.usage.setObjectName("usage")
        self.gridLayout_2.addWidget(self.usage, 0, 2, 1, 1)
        self.gridLayout.addWidget(self.widget_3, 4, 0, 1, 3)
        self.gridLayout_4.addWidget(self.widget_2, 0, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.centralwidget)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.dumpLog = QtWidgets.QPushButton(self.widget_4)
        self.dumpLog.setObjectName("dumpLog")
        self.gridLayout_3.addWidget(self.dumpLog, 8, 2, 1, 1)
        self.generate = QtWidgets.QPushButton(self.widget_4)
        self.generate.setMinimumSize(QtCore.QSize(200, 50))
        self.generate.setAutoRepeat(False)
        self.generate.setAutoExclusive(False)
        self.generate.setObjectName("generate")
        self.gridLayout_3.addWidget(self.generate, 0, 1, 1, 1)
        self.resAll = QtWidgets.QPushButton(self.widget_4)
        self.resAll.setObjectName("resAll")
        self.gridLayout_3.addWidget(self.resAll, 6, 2, 1, 1)
        self.resConsole = QtWidgets.QPushButton(self.widget_4)
        self.resConsole.setObjectName("resConsole")
        self.gridLayout_3.addWidget(self.resConsole, 7, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.widget_4, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.idir, self.browseidir)
        MainWindow.setTabOrder(self.browseidir, self.odir)
        MainWindow.setTabOrder(self.odir, self.browseodir)
        MainWindow.setTabOrder(self.browseodir, self.logo)
        MainWindow.setTabOrder(self.logo, self.browselogo)
        MainWindow.setTabOrder(self.browselogo, self.name)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Matlab Documentation Generator"))
        self.label_2.setText(_translate("MainWindow", "Output directory"))
        self.browseidir.setText(_translate("MainWindow", "..."))
        self.browseodir.setText(_translate("MainWindow", "..."))
        self.browselogo.setText(_translate("MainWindow", "..."))
        self.label_4.setText(_translate("MainWindow", "Project Name"))
        self.label_3.setText(_translate("MainWindow", "Project Logo"))
        self.label.setText(_translate("MainWindow", "Input directory"))
        self.verbose.setText(_translate("MainWindow", "Verbose mode"))
        self.code.setText(_translate("MainWindow", "Append Code"))
        self.recursive.setText(_translate("MainWindow", "Recursive scan"))
        self.usage.setText(_translate("MainWindow", "Check usage"))
        self.dumpLog.setText(_translate("MainWindow", "Dump log"))
        self.generate.setText(_translate("MainWindow", "Generate Documentation"))
        self.resAll.setText(_translate("MainWindow", "Reset All"))
        self.resConsole.setText(_translate("MainWindow", "Reset console"))

